---
apiVersion: v1
kind: IngressRoute
metadata:
  name: argocd-playground
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: PathPrefix(`/internal/playground`)
      kind: Rule
      services:
        - name: argocd-playground
          port: 80
